version: "3.8"

services:
  app:
    build: ./

  server:
    build: ../minecraftlegionwebserver
    command: npx nodemon -L index.js
    volumes:
      - ../minecraftlegionwebserver:/usr/src
      - /usr/src/node_modules

  web:
    build: ../minecraftlegionwebclient
    volumes:
      - ../minecraftlegionwebclient:/usr/src
      - /usr/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
