version: "3.8"

services:
  app:
    image: minecraftlegion
    environment:
      MONGO_URL: "mongodb://db:27017/minecraftlegion"
    depends_on:
      - db
    ports:
      - 3000:3000
  
  db:
    image: mongo
    ports:
      - 27017:27017
