version: "3.8"

services:
  app:
    container_name: minecraftlegion
    build: ./

  server:
    container_name: minecraftlegionwebserver
    build: ../minecraftlegionwebserver
    command: npx nodemon -L index.js
    volumes:
      - ../minecraftlegionwebserver:/usr/src
      - /usr/src/node_modules

  web:
    container_name: minecraftlegionwebclient
    build: ../minecraftlegionwebclient
    volumes:
      - ../minecraftlegionwebclient:/usr/src
      - /usr/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
